name: Run Azure Login without subscription

on: [push]

permissions:
  id-token: write # Necessary for Azure OIDC login
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Updated to use Node.js 20

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Needed for the login action
        allow-no-subscriptions: true
        enable-AzPSSession: true

    - name: Azure CLI script
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Run Azure PowerShell
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          Get-AzContext
